---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ngx
  namespace: default
data:
  default.conf: |
    ## /etc/nginx/conf.d/default.conf
    server {
        ## Accept PROXY Protocol 
        ### https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/
        ### listen PORT proxy_protocol;
        ### That configuration makes the following vars available:
        ### $proxy_protocol_addr : $proxy_protocol_port (Client's IP:PORT)
        ### $remote_addr : $remote_port (Downstream LB's IP:PORT)
        listen       80 proxy_protocol;
        listen  [::]:80 proxy_protocol;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        ## JSON-body response
        location /meta {
            add_header Content-Type application/json;
            return 200 '{"host": "$hostname", "client_ip": "$proxy_protocol_addr", "date": "$time_iso8601"}';
        }

        ## Redirect error pages to static page /50x.html
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
