---
apiVersion: v1
kind: Service
metadata:
  name: ngx
  namespace: default
  labels:
    app: ngx
spec:
  type: NodePort
  selector:
    app: ngx
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
